### ISSUE TITLE
how to use it !

### ISSUE THREAD

**Issue by iwwi** [romualdoandre/myomr#1]
Hello! im trying to use your OMR but I need to know how is the format, and what parameters need the test.py. Thx

**Comment by romualdoandre** [comment]
Sorry. I don't have an english tutorial yet. I will write a better Readme file with more instructions soon.

**Comment by iwwi** [comment]
thx XD

**Comment by romualdoandre** [comment]
I translated some documentation. I will make a video tutorial.

**Comment by rohinrohin** [comment]
@romualdoandre did you have a chance to make the video tutorial? I am trying to use it and I am finding it difficult to understand. Any help is appreciated.
